#!/usr/bin/env python
import os

I18N_PACKAGE = 'android-backend'

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features='cxx cxxshlib')
    obj.source = [
        'android_audiobackend.cc',
    ]
    obj.includes = ['.']
    obj.name = 'android_audiobackend'
    obj.target = 'android_audiobackend'
    obj.use = ['libardour', 'libpbd']
    obj.uselib = ['GLIBMM', 'XML', 'OBOE']
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'backends')
    obj.defines = [
        'PACKAGE="' + I18N_PACKAGE + '"',
        'ARDOURBACKEND_DLL_EXPORTS',
        'PLATFORM_ANDROID',
    ]
